services:
  - type: web
    name: diam-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    disk:
      name: diam-uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false 